cow_jokes = ["How much livestock is in your farm? I don't know I've lost cownt.",
                 "What does a scared cow do? It cowers.",
                 "What did the cow say when you told it a bad joke? 'I am not amoosed.'",
                 "What did the cow say when things didn't go its way? 'I am udderly disappointed'"]
ling_jokes = ["What is a linguist's favourite way to communicate? Using their phones.",
                           "Why was the linguist hired to do cold calls? They had great phone-ethics.",
                           "What did the linguist dress up as for Halloween? A corpus.",
                           "What do you call a hungry linguist? Nom Chompsky.",
                           "What is the field of linguistics' greatest sin? Tax."]
snake_jokes = ["My anaconda don't want none unless you got puns hun.",
                     "What is a snake's favourite programming language? Python."]

notrandompuns = ["Stop bugging me with these boring suggestions.", "I was bready to tell you a funny joke but then I forgot it.",
                 "This is a silly suggestion. Quit horsing around.",
                 "This is a silly suggestion. Quit foaling around.", "This suggestion is toadally cool, bro.",
                 "What a boaring suggestion. You could do better.", "The fact that WordNet thinks 'bull' has more semantic similarity to 'pig' than it has to 'cow' "
                    "is a load of bull."]

pundict = {"cow": cow_jokes,
           "cattle": cow_jokes,
           "horse": ["What did the horse say when it hadn't eaten for a while? 'I'm so hungry I could eat a human.'",
                   "I can't give you a pun today, I'm feeling too horse.",
                   "What do you call the horse next door? Your neighbour.",
                   "This is a silly suggestion. Quit horsing around.",
                   "This is a silly suggestion. Quit foaling around.",
                     "What do you call a slow horse? A stall-ion."],
           "pig": ["What a boaring suggestion. You could do better.",
                 "What does a french pig say when it's confused? 'Porkquoi?'",
                 "What do tourist pigs like to do? Take pigtures."],
           "fox": ["Give me a better suggestion. I couldn't give any fox about this one."],
           "llama": ["Do you want to go on a picnic today? Alpaca lunch! :]"],
           "toad": ["This suggestion is toadally cool, bro.",
                  "I read a book about amphibians today. It was ribbiting."],
           "otter": ["This is your suggestion? Get otter here!",
                   "If otters had their own country what would be their capital city? Otterwa."],
           "linguistics": ling_jokes,
           "linguist": ling_jokes,
           "wug": ["Wugs not drugs.",
                 "What is a linguist's favourite dog breed? A wug.",
                 "I didn't choose the wug life, the wug life chose me.",
                 "What do you call a linguist who needs plastic surgery? Wugly."],
           "snake": snake_jokes,
           "anaconda": snake_jokes,
           "python": snake_jokes,
           "adder": snake_jokes,
           "cobra": snake_jokes,
           "music": ["What do you call a pleasantly agreeable song? A mellowdy",
                     "How do you get hired in the music industry? You need to have a solid pitch."],
           "bug": ["Stop bugging me with these boring suggestions.",
                   "What do you call a bug detective? An insector."],
           "mango": ["Did you say mango? Man-go away!"],
           "berry": ["Do you like smoothies? I find them berry nice.",
                     "What should you do if your strawberry plant dies? Berry it."],
           "cheese": ["Cheese puns are difficult. I can never think of one that is gouda-nough.",
                      "What do you call a cheesy retelling of Cinderella? Mozzarella.",
                      "What do you call a cheesy pun but in French? Camembour.",
                      "You cheddar not suggest a cheese pun again."],
           "train":["How do conductors learn to do their job? They train."],
           "grass":["How can you thank your Spanish-speaking gardener? Grassias!"],
           "lemon": ["What does a lemon call when it's in a tight squeeze? Lemon-Aid."],
           "bread": ["I was bready to tell you a funny joke but then I forgot it."],
           "floor": ["I was bewildered when I walked into my apartment to discover someone stole my carpet. You could "
                     "say I was floored."],
           "box": ["What did the garbage can say to the blue box the day after garbage collection? Where have you bin?"],
           "planet": ["Why are aliens so good at carrying out an invasion? They planet."]}

